# Generated by Django 5.2.7 on 2025-10-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo_profie',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_profile',
            field=models.ImageField(blank=True, default='profile_photos/default.png', upload_to='profile_photos/'),
        ),
    ]
