# Generated by Django 5.2.7 on 2025-11-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_photo_profie_profile_photo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='user.profile'),
        ),
    ]
