# Generated by Django 5.2.7 on 2025-11-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_post_likes_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='context',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
